name: Deploy to telegram

on:
  workflow_dispatch: # allow jobs manual run
  release:
    types: [published]

jobs:
  send-to-telegram:
    name: send file to telegram
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: instalasi modules
        run: yarn

      - name: make gradle executable
        run: chmod +x ./android/gradlew

      - name: generate apk
        run: |
          cd android
          ./gradlew assembleRelease bundleRelease
          cd ..
      - name: Upload App to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_JSON }}
          packageName: com.bookapp.iqbal
          releaseFiles: android/app/build/outputs/bundle/release/*.aab
          track: alpha
          status: completed
          inAppUpdatePriority: 2

      - name: send to telegram
        run:
